name: Uzi - The German Sheperd
favicon: null
layout_spectrum: 0.34698
typography_spectrum: 0.15415
title: Uzi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090d0c'
    - '#ffffff'
    - '#564636'
    - '#c4b492'
    - '#968460'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
